### ISSUE TITLE
This add-on is not compatible with this version of kodi

### ISSUE THREAD

**Issue by neo-neo1** [firsttris/repository.sendtokodi.leia#2]
I installed this kodi repository and when I tried the install the latest sendtokodi add-on version 0.0.236.1 I received the error "This add-on is not compatible with this version of kodi". Im using Kodi 18.9 (latest version of CoreELEC) assuming this was an intentional upgrade to switch this add-on to Kodi 19, I suggest creating a separate Kodi add-on respistory for Kodi 19 and Kodi 18 like over devs have done so. Otherwise, the repository breaks things. I had to manually look through github for previous releases to install, troubleshoot why it wouldn't work, and finally settle the latest compatible version which was 0.0.225.1.

**Comment by firsttris** [comment]
thx for reporting, can you check if plugin.video.sendtokodi-0.0.237.1 + is working again ?

**Comment by neo-neo1** [comment]
0.0.237.1 works fine on Kodi 18.9, thank you.
