### ISSUE TITLE
Sendtokodi fails to update because of a small typo in addon.xml

### ISSUE THREAD

**Issue by pitsi** [firsttris/repository.sendtokodi.leia#3]
As mentioned in the title, the addon fails to update since yesterday with the following error
```
2021-11-05 12:42:46.020 T:139762416404224   ERROR: Failed to parse 'zip://special%3a%2f%2fhome%2faddons%2fpackages%2fplugin.video.sendtokodi-0.1.1423653728.zip/plugin.video.sendtokodi/addon.xml'
2021-11-05 12:42:46.020 T:139762416404224   ERROR: CAddonInstallJob[plugin.video.sendtokodi]: invalid package special://home/addons/packages/plugin.video.sendtokodi-0.1.1423653728.zip
```
The reason is that in line 2 of its addon.xml, the name parameter ends with 2 of these: " (I have no idea how they are called), so it breaks the whole structure of the file and kodi complains.

`<addon id="plugin.video.sendtokodi" name="sendtokodi"" version="0.1.1423653728" provider-name="firsttris">`

This is for kodi 18, i.e. the python2 version of the addon, and it is from libreelec 9.2.6 x64. I assume the same issue exists in the python3 version of it, because it has the same typo.

**Comment by firsttris** [comment]
thx will try to fix tonight

**Comment by firsttris** [comment]
fixed

**Comment by pitsi** [comment]
Thank you for the quick fix. I have not opened my libreelec system yet to check, but I will do it in a couple of minutes.
Please allow me one more question. Each (automated?) addon update now gets all the changes that were done every day by you?

**Comment by firsttris** [comment]
There is a Job which automatically creates a new version of the add-on with the newest youtube_dl version. 

Before this Job was running with Travis, but they stopped their free plan. So the Job was not running since 11 of June.

The day before yesterday I migrated to Github Actions which is now rebuilding the add-on every Sunday with the recent youtube_dl version.

**Comment by firsttris** [comment]
And of course if you do a change on the repository it also automatically builds a new version
